Fix GitHub Runner token retrieval and remove unused variables

diff --git a/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl b/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
--- a/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
+++ b/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
@@ -70,12 +70,21 @@ function setup_github_runner() {
 
   curl -sSfL $(curl -sSf https://api.github.com/repos/actions/runner/releases/latest | jq '.assets.[].browser_download_url' -r | egrep 'linux-x64-[0-9.]+tar.gz$') | tar zx
 
-  runner_token=$(curl -Ss \
-    -X POST \
-    -H "Accept: application/vnd.github+json" \
-    -H "Authorization: Bearer $${app_token}" \
-    -H "X-GitHub-Api-Version: 2022-11-28" \
-    -L "$${api_url}/repos/$${repository}/actions/runners/registration-token" | jq -r .token)
+  set +e
+  runner_token_response=$(curl -sS --fail-with-body\
+  -X POST \
+  -H "Accept: application/vnd.github+json" \
+  -H "Authorization: Bearer ${app_token}" \
+  -H "X-GitHub-Api-Version: 2022-11-28" \
+  -L "${api_url}/repos/${repository}/actions/runners/registration-token" )
+  exit_code=$?
+  set -e
+
+  runner_token=$(echo $${runner_token_response} | jq -r .token)
+  if [[ 0 != $${exit_code} ]]; then
+    echo "Failed to get the GitHub Runner token: $${runner_token_response}"
+    exit 1
+  fi
 
   sudo chown -R "$${local_user}" $${agent_home}
 
